
POST http://localhost:8000/process-single/
Content-Type: application/json

{
  "sortList": [[1, 7, 3, 6], [2, 4, 5, 1], [8, 1, 4]]
}

###
POST http://localhost:8000/process-concurrent
Content-Type: application/json

{
  "to_sort": [[1, 7, 3, 6], [2, 4, 5, 1], [8, 1, 4]]
}



